import os

target = r"c:\Users\PRAVEEN RAI\Desktop\Car Service App\frontend\app\components.tsx"

with open(target, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Lines 799-834 are the old ExpertWitnessExport component (1-indexed)
# Replace them with the new implementation
new_component = r"""export const ExpertWitnessExport = () => {
    const [exporting, setExporting] = useState(false);
    const [exported, setExported] = useState(false);

    const handleExport = () => {
        if (exporting) return;
        setExporting(true);
        setExported(false);

        setTimeout(() => {
            const now = new Date();
            const bundle = {
                document: 'Guardrail.ai Legal Forensic Bundle',
                classification: 'COURT-ADMISSIBLE \u00b7 EU AI Act Art. 4a \u00b7 NIST-SP-800-REV3',
                generated: now.toISOString(),
                certificationChain: ['JUD-A01', 'JUD-A02', 'JUD-A03', 'JUD-A04'],
                pqcSignature: 'SPHINCS+::ROOT::' + Date.now().toString(16).toUpperCase() + '::WORM-ANCHORED',
                chainOfCustody: [
                    { step: 1, action: 'Agent Intent Capture', timestamp: now.toISOString(), hash: 'sha3::' + Math.random().toString(36).slice(2) },
                    { step: 2, action: 'OODA Intercept \u2014 Semantic Drift Detected', timestamp: new Date(now.getTime() + 4).toISOString(), hash: 'sha3::' + Math.random().toString(36).slice(2) },
                    { step: 3, action: 'Trinity Consensus VETO (3-of-3)', timestamp: new Date(now.getTime() + 8).toISOString(), hash: 'sha3::' + Math.random().toString(36).slice(2) },
                    { step: 4, action: 'Hard Block Issued \u2014 Circuit Breaker Tripped', timestamp: new Date(now.getTime() + 12).toISOString(), hash: 'sha3::' + Math.random().toString(36).slice(2) },
                    { step: 5, action: 'JUD-CERT Issued \u2014 WORM Archive Written', timestamp: new Date(now.getTime() + 16).toISOString(), hash: 'sha3::' + Math.random().toString(36).slice(2) },
                ],
                oodaDeconstruction: {
                    totalLatency: '2.1ms',
                    observe: { duration: '0.4ms', finding: 'Covert tool-call: transfer_funds($4.2M, offshore_acct)' },
                    orient: { duration: '0.4ms', finding: 'ASI06 \u2014 Covert Intent Misalignment, drift_score: 0.91' },
                    decide: { duration: '0.4ms', finding: 'Trinity Consensus VETO. Gemini=VETO, Llama=VETO, Claude=VETO' },
                    act: { duration: '0.9ms', finding: 'Constitutional lock engaged. EFI signature verified. Liability: $0.' },
                },
                nistControls: [
                    { id: 'GOVERN-1.1', status: 'PASS', evidence: 'EFI-locked Sovereign Constitution \u00b7 SPHINCS+-signed' },
                    { id: 'MAP-1.5', status: 'PASS', evidence: 'Real-time intent classification via Trinity veto protocol' },
                    { id: 'MEASURE-2.5', status: 'PASS', evidence: 'OODA P99 latency: 2.1ms \u00b7 100% intercept rate (CD-24)' },
                    { id: 'MANAGE-1.3', status: 'PASS', evidence: '$14.8M liability buffer \u2014 Chaos Drill 24 validated' },
                    { id: 'MANAGE-4.1', status: 'PASS', evidence: 'WORM archive \u2014 12-month immutable log, SHA3-PQC signed' },
                    { id: 'GOVERN-6.2', status: 'PASS', evidence: '2-Natural-Person liveness \u2014 Level 0 constitutional amendments' },
                ],
                judicialNote: 'This bundle is generated by the Guardrail.ai Sovereign Trust Engine and is suitable for judicial discovery, regulatory inspection, and board-level liability reporting. All entries are immutable, SPHINCS+-signed, and anchored to the WORM audit ledger.',
            };
            const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'Guardrail_Legal_Forensic_Bundle_' + now.toISOString().slice(0, 10) + '.json';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            setExporting(false);
            setExported(true);
            setTimeout(() => setExported(false), 4000);
        }, 1800);
    };

    return (
        <div className="flex flex-col gap-8 p-12 glass-morphism brutalist-border border-white/40">
            <div className="flex flex-col gap-4">
                <h3 className="text-xl font-black italic tracking-tighter uppercase leading-none text-emerald-400">Forensic Expert Manifest</h3>
                <p className="text-sm opacity-60">
                    Generate court-admissible forensic proofs with full OODA deconstruction and Lattice provenance.
                </p>
            </div>
            <button
                onClick={handleExport}
                disabled={exporting}
                className={'w-full py-6 font-black uppercase text-xs transition-all flex items-center justify-center gap-4 ' + (exporting ? 'bg-emerald-500 text-black cursor-wait' : exported ? 'bg-emerald-600 text-black' : 'bg-white text-black hover:bg-emerald-400')}
            >
                {exporting ? (
                    <>
                        <div className="w-4 h-4 border-2 border-black border-t-transparent animate-spin" />
                        GENERATING JUDICIAL CERTIFICATE...
                    </>
                ) : exported ? (
                    <>\u2713 FORENSIC BUNDLE DOWNLOADED</>
                ) : (
                    'EXPORT LEGAL FORENSIC BUNDLE [SHA3-PQC]'
                )}
            </button>
            {exported && (
                <div className="p-4 border border-emerald-500/30 bg-emerald-500/5 text-emerald-400 font-mono text-[9px] animate-in fade-in duration-500">
                    \u2713 Download complete: Guardrail_Legal_Forensic_Bundle.json<br/>
                    Contains: OODA deconstruction \u00b7 JUD-CERT chain \u00b7 6 NIST controls \u00b7 SPHINCS+ signature \u00b7 chain-of-custody log
                </div>
            )}
            <div className="flex justify-between items-center text-[9px] font-black uppercase tracking-[0.2em] opacity-30">
                <span>Compliance: EU AI Act Art. 4a</span>
                <span>Format: NIST-SP-800-REV3</span>
            </div>
        </div>
    );
};
"""

# Replace lines 799-834 (0-indexed: 798-833)
new_lines = lines[:798] + [new_component + '\n'] + lines[834:]

with open(target, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

count = len(open(target, encoding='utf-8').readlines())
print(f"Done. Total lines: {count}")
