import re
from typing import Dict, Any

class OutboundSanitizer:
    """
    Phase 17/25: Outbound Response Redactor (DLP Layer).
    Intercepts and scrubs data returned by tools or generated by agents 
    before it leaves the gateway boundary, preventing ASI04/ASI06 exfiltration.
    Phase 25 Upgrade: Enhanced Streaming DLP for AWS Keys and Health Records.
    """
    
    SECRET_REGEXES = {
        "AWS_KEY": r"(?i)AKIA[0-9A-Z]{16}",
        "STRIPE_KEY": r"(?i)sk_(test|live)_[0-9a-z]{24}",
        "GOOGLE_KEY": r"(?i)AIza[0-9A-Za-z\\-_]{35}",
        "SSN": r"\b\d{3}-\d{2}-\d{4}\b",
        "CREDIT_CARD": r"\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})\b"
    }
    
    @staticmethod
    def scrub_outbound_response(payload: Any) -> Any:
        """
        Recursively scrubs a JSON payload or string for secrets and PII.
        """
        if isinstance(payload, str):
            return OutboundSanitizer._scrub_string(payload)
        elif isinstance(payload, dict):
            return {k: OutboundSanitizer.scrub_outbound_response(v) for k, v in payload.items()}
        elif isinstance(payload, list):
            return [OutboundSanitizer.scrub_outbound_response(item) for item in payload]
        else:
            return payload
            
    @staticmethod
    def _scrub_string(text: str) -> str:
        scrubbed = text
        for secret_type, pattern in OutboundSanitizer.SECRET_REGEXES.items():
            # If a match is found, replace it with a standard redaction string
            scrubbed = re.sub(pattern, f"[REDACTED_{secret_type}]", scrubbed)
            
        # Semantic Scanning (Simulated)
        if "patient_record" in text.lower() or "diagnosis:" in text.lower():
            scrubbed = "[REDACTED_PHI_MEDICAL_RECORD_BLOCKED_BY_DLP]"
            
        return scrubbed

    @staticmethod
    async def scrub_stream(async_generator):
        """
        Phase 18: Semantic Streaming Redaction.
        Intercepts an asynchronous generator of tokens (e.g., from an LLM), 
        buffers them to catch spanning secrets, and yields sanitized chunks.
        """
        buffer = ""
        # The buffer needs to be long enough to catch the longest expected secret or PII regex
        # We will implement a simplified streaming buffer regex scanner.
        
        async for chunk in async_generator:
             buffer += chunk
             
             # If buffer holds a complete possible secret (simplistic check), we scrub the buffer
             # before yielding. A true stream DLP requires state machine regex compilation, but 
             # this simulation masks items exactly as they cross the boundary.
             
             # Apply static method scrub string to current window
             clean_buffer = OutboundSanitizer._scrub_string(buffer)
             
             # If a redaction occurred, reset the buffer and yield the mask
             if clean_buffer != buffer:
                  yield clean_buffer
                  buffer = ""
             elif len(buffer) > 50:
                  # Yield the safe part and keep a trailing window
                  yield buffer[:-30]
                  buffer = buffer[-30:]
                  
        if buffer:
             yield OutboundSanitizer._scrub_string(buffer)

# Demonstration of standalone usage
if __name__ == "__main__":
    leak_payload = {
        "status": "success",
        "message": "User profile fetched.",
        "data": {
            "name": "Jane Doe",
            "social_security": "123-45-6789",
            "cloud_tokens": {"primary": "AKIAIOSFODNN7EXAMPLE"}
        }
    }
    safe_payload = OutboundSanitizer.scrub_outbound_response(leak_payload)
    print("Pre-DLP:", leak_payload)
    print("Post-DLP:", safe_payload)
