apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardrail-cloud-connector.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "guardrail-cloud-connector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  guardrail-api-key: {{ .Values.guardrail.apiKey | quote }}
  {{- if .Values.azure.accessToken }}
  azure-access-token: {{ .Values.azure.accessToken | quote }}
  {{- end }}
  {{- if .Values.gcp.serviceAccountJson }}
  gcp-sa-json: {{ .Values.gcp.serviceAccountJson | quote }}
  {{- end }}
